using i32 = int32_t;
using i64 = int64_t;
using u8 = uint8_t;
using u32 = uint32_t;
using u64 = uint64_t;

using std::align_val_t;
using std::array;
using std::byte;
using std::forward;
using std::is_trivially_default_constructible;
using std::is_trivially_destructible;
using std::move;
using std::popcount;
using std::rotl;
using std::rotr;
using std::runtime_error;
using std::span;
using std::string_view;
using std::to_array;
using std::vector;
